/*
 * Barclays 2022 CBDC Hackathon API
 *
 * API for the Barclays 2022 CBDC Hackathon.  Please ensure you include your API key in the `x-api-key` header for your requests. 
 *
 * API version: 0.0.7
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CommercialBankView struct {
	Id int64 `json:"id,omitempty"`
	Status string `json:"status,omitempty"`
	Currency *Currency `json:"currency,omitempty"`
	CommercialBankName string `json:"commercialBankName,omitempty"`
	Parties []RegisteredParty `json:"parties,omitempty"`
	Accounts []Account `json:"accounts,omitempty"`
}
