/*
 * Barclays 2022 CBDC Hackathon API
 *
 * API for the Barclays 2022 CBDC Hackathon.  Please ensure you include your API key in the `x-api-key` header for your requests. 
 *
 * API version: 0.0.7
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CurrencyView struct {
	Id int64 `json:"id,omitempty"`
	Status string `json:"status,omitempty"`
	CurrencyDetails *Currency `json:"currencyDetails,omitempty"`
	CbdcAccounts []CbdcAccountChild `json:"cbdcAccounts,omitempty"`
	CommercialBanks []CommercialBankChild `json:"commercialBanks,omitempty"`
	Pips []PipChild `json:"pips,omitempty"`
}
