/*
 * Barclays 2022 CBDC Hackathon API
 *
 * API for the Barclays 2022 CBDC Hackathon.  Please ensure you include your API key in the `x-api-key` header for your requests. 
 *
 * API version: 0.0.7
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GetCurrencyDetailsPageResponseBody struct {
	Data []CurrencyView `json:"data,omitempty"`
	First bool `json:"first,omitempty"`
	Last bool `json:"last,omitempty"`
	TotalPages int32 `json:"totalPages,omitempty"`
	TotalElements int64 `json:"totalElements,omitempty"`
	PageSize int32 `json:"pageSize,omitempty"`
	PageIndex int32 `json:"pageIndex,omitempty"`
	PageNumberOfElements int32 `json:"pageNumberOfElements,omitempty"`
}
